server:
  port: 8899
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

spring:
  # 数据源
  datasource:
    dynamic:
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 100
        min-idle: 5
        connection-test-query: select 1
        pool-name: DemoHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: postgres
          password: postgres
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/phlink_demo
      # 数据源-2，名称为 test
#        test:
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/bus_test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  #redis
  redis:
    database: 0
    password: qwe@123
    timeout: 3000
    #sentinel/cluster/single
    mode: single
    codec: org.redisson.codec.JsonJacksonCodec
    pool:
      #连接池配置
      max-idle: 16
      min-idle: 8
      max-active: 8
      max-wait: 3000
      conn-timeout: 3000
      so-timeout: 3000
      size: 10
    #单机配置
    single:
      address: "redis://127.0.0.1:6379"
    #集群配置
    cluster:
      scan-interval: 1000
      nodes:
          - "redis://127.0.0.1:7004"
          - "redis://127.0.0.1:7001"
          - "redis://127.0.0.1:7000"
      read-mode: SLAVE
      retry-attempts: 3
      failed-attempts: 3
      slave-connection-pool-size: 64
      master-connection-pool-size: 64
      retry-interval: 1500
    #哨兵配置
    sentinel:
      master: business-master
      nodes:
        - "redis://127.0.0.1:7004"
        - "redis://127.0.0.1:7001"
        - "redis://127.0.0.1:7000"
      master-onlyWrite: true
      fail-max: 3
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers:
      - 10.1.8.177:9092
      - 10.1.8.177:9093
    consumer:
      enable-auto-commit: true
      group-id: kaDemo
      auto-offset-reset: latest
      bootstrap-servers:
        - 10.1.8.177:9092
        - 10.1.8.177:9093


  # 文件大小上传配置
  messages:
    encoding: utf-8

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail-on-empty-beans: false


management:
  endpoint:
    health:
      show-details: always
      status:
        http-mapping:
          DOWN: 200
          OUT_OF_SERVICE: 200
          FATAL: 200
          UNKNOWN: 200
  endpoints:
    web:
      base-path: /actuator/
      exposure:
        include: '*'

phlink:
  # 全局限流
  ratelimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制200个请求
    limit: 200
  # IP限流
  iplimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 每个ip限制20个请求
    limit: 20
  # token交互方式
  token:
    # 设置为true后，token将存入redis，并具有单点登录功能 默认false使用JWT交互
    redis: true
    # 是否开启单设备登陆 仅当token交互方式为redis时生效
    sdl: true
    # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
    # token过期时间（分钟）
    tokenExpireTime: 60
    # 用户选择保存登录状态对应token过期时间（天）
    saveLoginTime: 7
    # 限制用户登陆错误次数（次）
    loginTimeLimit: 10
    # 错误超过次数后多少分钟后才能继续登录（分钟）
    loginAfterTime: 10
  boot:
    admin:
      # 修改上下文路径
      context-path: /admin
      client:
        url: http://127.0.0.1:${server.port}/admin


fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 127.0.0.1:22122

# 需要验证码校验的接口路径 支持通配符 自动过滤拦截校验 无需开发人员再次校验
captcha:
  image:
    - /login
    - /oauth2/authorize
  username:
    - /login/username
  sms:
    - /login/mobile

# 忽略鉴权url
ignored:
  urls:
    - /oauth2/**
    - /actuator/**
    - /admin/**
    - /dictData/getByType/**
    - /user/regist
    - /common/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /*/test/**

# Swagger界面内容配置
swagger:
  title: Phlink API接口文档
  description: Phlink Api Documentation
  version: 1.0.0
  termsOfServiceUrl: http://puhuilink.com
  contact:
    name: wen wen
    url: http://puhuilink.com
    email: wenwen@puhuilink.com

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

# 日志
logging:
  # 输出级别
  level:
    root: info
  file:
    # 指定路径
    path: phlink-logs
    # 最大保存天数
    max-history: 7
    # 每个文件最大大小
    max-size: 5MB